# LANDING

In [1]:
   import duckdb
   import pandas as pd
   import os
   from datetime import datetime

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [3]:
con.execute("""DROP TABLE IF EXISTS bronze_produtos""")

In [4]:
arquivo  = 'z0019_1.csv'
data_ingestao = datetime.now()
df1 = pd.read_csv(f'../landing/{arquivo}', sep=';')
df1['nome_arquivo'] = arquivo
df1['data_ingestao'] = data_ingestao
df1.head(20)

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_arquivo,data_ingestao
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-01-11 17:57:43.739535
2,10003,PORCA,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
3,10004,ARRUELA,BT10,100,1000,z0019_1.csv,2026-01-11 17:57:43.739535
4,10005,PREGO,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
5,10006,BUCHA,BT10,100,1500,z0019_1.csv,2026-01-11 17:57:43.739535
6,10007,REBITE,BT10,100,2000,z0019_1.csv,2026-01-11 17:57:43.739535
7,10008,CHAVE,BT10,100,300,z0019_1.csv,2026-01-11 17:57:43.739535
8,10009,PARAFUSADEIRA,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
9,10010,ALICATE,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
10,10011,TRENA,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
11,10012,NIVEL,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535

In [9]:
arquivo  = 'z0019_2.csv'
data_ingestao = datetime.now()
df2 = pd.read_csv(f'../landing/{arquivo}', sep=';')
df2['nome_arquivo'] = arquivo
df2['data_ingestao'] = data_ingestao
df2.head(20)

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_arquivo,data_ingestao
0,10013,ESQUADRO,BT10,100,400,z0019_2.csv,2026-01-11 17:58:21.701522
1,10014,TALHADEIRA,BT10,100,200,z0019_2.csv,2026-01-11 17:58:21.701522
2,10015,PONTEIRO,BT10,100,150,z0019_2.csv,2026-01-11 17:58:21.701522
3,10016,LIXA,BT10,100,2000,z0019_2.csv,2026-01-11 17:58:21.701522
4,10005,PREGO,BT10,100,60,z0019_2.csv,2026-01-11 17:58:21.701522

# BRONZE

In [6]:
# bronze_produtos

con.execute("""
   CREATE TABLE IF NOT EXISTS bronze_produtos(
      NATBR VARCHAR,
      MAKTX VARCHAR,
      WERKS VARCHAR,
      MAINS VARCHAR,
      LABST VARCHAR,
      nome_arquivo VARCHAR,
      data_ingestao TIMESTAMP
   );
""")

In [13]:
# Limpa a tabela para não acumular lixo de execuções anteriores
con.execute("DELETE FROM bronze_produtos")

# Insere o primeiro lote
con.execute("INSERT INTO bronze_produtos SELECT * FROM df1")

# Insere o segundo lote
con.execute("INSERT INTO bronze_produtos SELECT * FROM df2")

# Consulta para validar (ordenando para ver os novos no topo ou fim)
resultado = con.execute("SELECT * FROM bronze_produtos").df()
display(resultado)

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_arquivo,data_ingestao
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-01-11 17:57:43.739535
2,10003,PORCA,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
3,10004,ARRUELA,BT10,100,1000,z0019_1.csv,2026-01-11 17:57:43.739535
4,10005,PREGO,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
5,10006,BUCHA,BT10,100,1500,z0019_1.csv,2026-01-11 17:57:43.739535
6,10007,REBITE,BT10,100,2000,z0019_1.csv,2026-01-11 17:57:43.739535
7,10008,CHAVE,BT10,100,300,z0019_1.csv,2026-01-11 17:57:43.739535
8,10009,PARAFUSADEIRA,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
9,10010,ALICATE,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
10,10011,TRENA,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
11,10012,NIVEL,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
12,10013,ESQUADRO,BT10,100,400,z0019_2.csv,2026-01-11 17:58:21.701522
13,10014,TALHADEIRA,BT10,100,200,z0019_2.csv,2026-01-11 17:58:21.701522
14,10015,PONTEIRO,BT10,100,150,z0019_2.csv,2026-01-11 17:58:21.701522
15,10016,LIXA,BT10,100,2000,z0019_2.csv,2026-01-11 17:58:21.701522
16,10005,PREGO,BT10,100,60,z0019_2.csv,2026-01-11 17:58:21.701522

In [15]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [16]:
resultado = con.execute("SELECT * FROM bronze_z0019").df()
display(resultado)

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_arquivo,data_ingestao
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-01-11 17:57:43.739535
2,10003,PORCA,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
3,10004,ARRUELA,BT10,100,1000,z0019_1.csv,2026-01-11 17:57:43.739535
4,10005,PREGO,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
5,10006,BUCHA,BT10,100,1500,z0019_1.csv,2026-01-11 17:57:43.739535
6,10007,REBITE,BT10,100,2000,z0019_1.csv,2026-01-11 17:57:43.739535
7,10008,CHAVE,BT10,100,300,z0019_1.csv,2026-01-11 17:57:43.739535
8,10009,PARAFUSADEIRA,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
9,10010,ALICATE,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
10,10011,TRENA,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
11,10012,NIVEL,BT10,100,100,z0019_1.csv,2026-01-11 17:57:43.739535
12,10013,ESQUADRO,BT10,100,400,z0019_2.csv,2026-01-11 17:58:21.701522
13,10014,TALHADEIRA,BT10,100,200,z0019_2.csv,2026-01-11 17:58:21.701522
14,10015,PONTEIRO,BT10,100,150,z0019_2.csv,2026-01-11 17:58:21.701522
15,10016,LIXA,BT10,100,2000,z0019_2.csv,2026-01-11 17:58:21.701522
16,10005,PREGO,BT10,100,60,z0019_2.csv,2026-01-11 17:58:21.701522

In [17]:
con.close()